import JSZip from "jszip";
import { GeneratedCode } from "@/store/projectStore";

export const exportService = {
  // 1. Copy code helper
  copyToClipboard: async (text: string): Promise<boolean> => {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      return false;
    }
  },

  // 2. Standalone HTML single-file download
  downloadHTMLProject: (code: GeneratedCode, name: string) => {
    const filename = `${name.toLowerCase().replace(/\s+/g, "-")}-html.html`;
    // Try multi-file: look for index.html or entry file
    const htmlContent = code.files?.["index.html"] || code.html || "";
    const cssContent = code.files?.["style.css"] || code.css || "";
    const jsContent = code.files?.["script.js"] || code.js || "";

    const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${name}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lucide-static@0.407.0/font/lucide.css">
  <style>
    ${cssContent}
  </style>
</head>
<body class="bg-slate-950 text-white min-h-screen">
  ${htmlContent || `<div id="root"></div>`}
  
  <script>
    ${jsContent}
  </script>
</body>
</html>`;

    triggerBlobDownload(fullHtml, "text/html", filename);
  },

  // 3. Standalone React single-file download (entry point)
  downloadReactFile: (code: GeneratedCode, name: string) => {
    const filename = `${name.split(" ")[0] || "App"}.tsx`;
    const entryContent = (code.files && code.entryPath && code.files[code.entryPath]) || code.react || "";
    triggerBlobDownload(entryContent, "text/typescript", filename);
  },

  // 4. Download React SPA full project setup (ZIP) with multi-file support
  downloadReactProject: async (code: GeneratedCode, name: string) => {
    const zip = new JSZip();
    const folderName = `${name.toLowerCase().replace(/\s+/g, "-")}-react`;

    const packageJson = {
      name: folderName,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^18.3.0",
        "react-dom": "^18.3.0",
        "lucide-react": "^0.471.0",
      },
      devDependencies: {
        "@types/react": "^18.3.0",
        "@types/react-dom": "^18.3.0",
        "@vitejs/plugin-react": "^4.3.0",
        typescript: "^5.0.0",
        vite: "^5.4.0",
        tailwindcss: "^3.4.0",
        autoprefixer: "^10.0.0",
        postcss: "^8.0.0",
      },
    };

    const viteConfig = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { '@': path.resolve(__dirname, './src') }
  }
});`;

    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
};`;

    const postcssConfig = `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };`;

    const indexHtml = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`;

    const mainTsx = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;

    const indexCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  background-color: #020617;
  color: #f8fafc;
  margin: 0;
}`;

    const tsconfig = `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}`;

    const readme = `# ${name}

Generated by [Cognify-AI](https://cognify-ai.local).

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
`;

    zip.file("package.json", JSON.stringify(packageJson, null, 2));
    zip.file("vite.config.ts", viteConfig);
    zip.file("tailwind.config.js", tailwindConfig);
    zip.file("postcss.config.js", postcssConfig);
    zip.file("tsconfig.json", tsconfig);
    zip.file("index.html", indexHtml);
    zip.file("README.md", readme);

    // Add all generated files to src/
    if (code.files && Object.keys(code.files).length > 0) {
      for (const [filePath, content] of Object.entries(code.files)) {
        zip.file(filePath, content);
      }
      // Ensure main.tsx and index.css exist
      if (!code.files["src/main.tsx"]) {
        zip.file("src/main.tsx", mainTsx);
      }
      if (!code.files["src/index.css"]) {
        zip.file("src/index.css", indexCss);
      }
    } else {
      // Legacy fallback
      zip.file("src/App.tsx", code.react || "");
      zip.file("src/main.tsx", mainTsx);
      zip.file("src/index.css", code.css ? `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n${code.css}` : indexCss);
    }

    const content = await zip.generateAsync({ type: "blob" });
    triggerBlobDownload(content, "application/zip", `${folderName}.zip`);
  },

  // 5. Download Next.js full project setup (ZIP) with multi-file support
  downloadNextJsProject: async (code: GeneratedCode, name: string) => {
    const zip = new JSZip();
    const folderName = `${name.toLowerCase().replace(/\s+/g, "-")}-nextjs`;

    const packageJson = {
      name: folderName,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        next: "15.1.0",
        "lucide-react": "^0.471.0",
      },
      devDependencies: {
        typescript: "^5.0.0",
        "@types/node": "^20.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        postcss: "^8.0.0",
        tailwindcss: "^3.4.0",
        autoprefixer: "^10.0.0",
      },
    };

    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: { extend: {} },
  plugins: [],
};`;

    const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;`;

    const tsconfig = `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`;

    const cssContent = code.files?.["src/index.css"] || code.css || "";
    const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  background-color: #020617;
  color: #f8fafc;
}
${cssContent}`;

    const layout = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by Cognify AI",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`;

    zip.file("package.json", JSON.stringify(packageJson, null, 2));
    zip.file("tailwind.config.js", tailwindConfig);
    zip.file("next.config.mjs", nextConfig);
    zip.file("tsconfig.json", tsconfig);

    // Add all generated files
    if (code.files && Object.keys(code.files).length > 0) {
      for (const [filePath, content] of Object.entries(code.files)) {
        // Skip index.css—globals.css already handles it
        if (filePath === "src/index.css") continue;
        // Re-route App.tsx to app/page.tsx if it's a Next.js project
        if (filePath === "src/App.tsx" && code.projectType === "nextjs") {
          zip.file("src/app/page.tsx", content);
        } else {
          zip.file(filePath, content);
        }
      }
    } else {
      // Legacy fallback
      const entryCode = code.react || "";
      zip.file("src/app/page.tsx", entryCode);
    }

    zip.file("src/app/globals.css", globalsCss);
    zip.file("src/app/layout.tsx", layout);

    const content = await zip.generateAsync({ type: "blob" });
    triggerBlobDownload(content, "application/zip", `${folderName}.zip`);
  },

  // 6. Download complete ZIP containing all files
  downloadFullZipProject: async (code: GeneratedCode, name: string) => {
    const zip = new JSZip();
    const folderName = `${name.toLowerCase().replace(/\s+/g, "-")}-workspace`;

    if (code.files && Object.keys(code.files).length > 0) {
      for (const [filePath, content] of Object.entries(code.files)) {
        zip.file(filePath, content);
      }
    } else {
      // Legacy fallback
      if (code.react) zip.file("App.tsx", code.react);
      if (code.html) zip.file("index.html", code.html);
      if (code.css) zip.file("style.css", code.css);
      if (code.js) zip.file("script.js", code.js);
    }

    const content = await zip.generateAsync({ type: "blob" });
    triggerBlobDownload(content, "application/zip", `${folderName}.zip`);
  },
};

function triggerBlobDownload(content: Blob | string, mimeType: string, filename: string) {
  const blob =
    typeof content === "string"
      ? new Blob([content], { type: `${mimeType};charset=utf-8` })
      : content;
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
