"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import {
  ArrowRight,
  Code2,
  PlayCircle,
  Sparkles,
  Wand2,
  Zap,
  CheckCircle2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  show: (i: number = 0) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.55, delay: i * 0.08, ease: [0.22, 1, 0.36, 1] },
  }),
};

const codeSnippet = `// Generated by Cognify-AI ✨
export function HeroSection() {
  return (
    <section className="hero gradient-bg">
      <h1>Build Faster with AI</h1>
      <Button>Get Started Free</Button>
    </section>
  );
}`;

const codeLines = codeSnippet.split("\n");

export function HeroSection() {
  return (
    <section
      className="relative overflow-hidden"
      aria-labelledby="hero-heading"
    >
      {/* Background mesh */}
      <div className="pointer-events-none absolute inset-0 bg-mesh-primary" aria-hidden="true" />
      {/* Gradient blobs */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true">
        <div className="absolute -top-40 left-1/2 h-[600px] w-[600px] -translate-x-1/2 rounded-full bg-primary-500/15 blur-3xl" />
        <div className="absolute -bottom-40 -left-20 h-[480px] w-[480px] rounded-full bg-accent-500/10 blur-3xl" />
        <div className="absolute -right-20 top-10 h-[400px] w-[400px] rounded-full bg-secondary-500/12 blur-3xl" />
      </div>

      <div className="section-container relative py-20 sm:py-28 lg:py-32">
        <div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-16">

          {/* ── Left: Copy ─────────────────────────────────── */}
          <div className="space-y-8">
            {/* Eyebrow badge */}
            <motion.div
              custom={0}
              variants={fadeUp}
              initial="hidden"
              animate="show"
            >
              <Badge variant="default" className="gap-2 py-1.5 px-4 text-sm">
                <Sparkles className="h-3.5 w-3.5" aria-hidden="true" />
                AI-Powered Frontend Generation
              </Badge>
            </motion.div>

            {/* Headline */}
            <motion.h1
              id="hero-heading"
              custom={1}
              variants={fadeUp}
              initial="hidden"
              animate="show"
              className="font-display text-balance text-5xl font-bold leading-[1.1] tracking-tight sm:text-6xl lg:text-7xl"
            >
              Transform Ideas into{" "}
              <span className="gradient-text">
                Beautiful UI
              </span>{" "}
              Instantly
            </motion.h1>

            {/* Subheading */}
            <motion.p
              custom={2}
              variants={fadeUp}
              initial="hidden"
              animate="show"
              className="max-w-xl text-pretty text-lg leading-relaxed text-gray-600 dark:text-gray-300"
            >
              Describe your UI in plain English. Cognify-AI generates production-ready
              React, HTML, and Tailwind code — with live preview and one-click export.
            </motion.p>

            {/* Trust signals */}
            <motion.ul
              custom={3}
              variants={fadeUp}
              initial="hidden"
              animate="show"
              className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-gray-600 dark:text-gray-400"
              aria-label="Key benefits"
            >
              {[
                "No backend required",
                "Instant live preview",
                "Export-ready code",
              ].map((item) => (
                <li key={item} className="flex items-center gap-1.5">
                  <CheckCircle2 className="h-4 w-4 text-green-500" aria-hidden="true" />
                  {item}
                </li>
              ))}
            </motion.ul>

            {/* CTAs */}
            <motion.div
              custom={4}
              variants={fadeUp}
              initial="hidden"
              animate="show"
              className="flex flex-wrap gap-4"
            >
              <Button size="lg" className="group shadow-glow-sm">
                <Link href="/register" className="flex items-center gap-2">
                  Start Building Free
                  <ArrowRight
                    className="h-4 w-4 transition-transform duration-200 group-hover:translate-x-1"
                    aria-hidden="true"
                  />
                </Link>
              </Button>
              <Button size="lg" variant="secondary">
                <Link href="#how-it-works" className="flex items-center gap-2">
                  <PlayCircle className="h-4 w-4" aria-hidden="true" />
                  See How It Works
                </Link>
              </Button>
            </motion.div>

            {/* Social proof */}
            <motion.div
              custom={5}
              variants={fadeUp}
              initial="hidden"
              animate="show"
              className="flex items-center gap-4 border-t border-gray-100 pt-6 dark:border-gray-800"
            >
              <div className="flex -space-x-2">
                {["AV", "NP", "SM", "EW", "JL"].map((initials, i) => (
                  <div
                    key={initials}
                    className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-white text-[10px] font-bold text-white dark:border-gray-950"
                    style={{
                      background: `hsl(${(i * 67 + 230) % 360} 70% 55%)`,
                    }}
                    aria-hidden="true"
                  >
                    {initials}
                  </div>
                ))}
              </div>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                <span className="font-semibold text-gray-900 dark:text-gray-100">
                  2,400+
                </span>{" "}
                developers building with Cognify-AI
              </p>
            </motion.div>
          </div>

          {/* ── Right: Code Preview Card ────────────────────── */}
          <motion.div
            custom={2}
            variants={fadeUp}
            initial="hidden"
            animate="show"
            className="relative"
          >
            {/* Glow behind card */}
            <div
              className="absolute inset-0 -z-10 rounded-3xl bg-gradient-to-tr from-primary-500/20 via-secondary-500/15 to-accent-500/15 blur-2xl"
              aria-hidden="true"
            />

            {/* Main card */}
            <div className="overflow-hidden rounded-3xl border border-gray-200/60 bg-white/80 shadow-card-hover backdrop-blur-sm dark:border-gray-700/40 dark:bg-gray-900/80">
              {/* Window chrome */}
              <div className="flex items-center justify-between border-b border-gray-200/60 bg-gray-50/80 px-5 py-3.5 dark:border-gray-700/40 dark:bg-gray-800/60">
                <div className="flex items-center gap-2">
                  <div className="h-3 w-3 rounded-full bg-red-400" aria-hidden="true" />
                  <div className="h-3 w-3 rounded-full bg-amber-400" aria-hidden="true" />
                  <div className="h-3 w-3 rounded-full bg-green-400" aria-hidden="true" />
                </div>
                <div className="flex items-center gap-2 rounded-lg bg-white/70 px-3 py-1 text-xs font-medium text-gray-500 dark:bg-gray-700/60 dark:text-gray-400">
                  <Wand2 className="h-3 w-3 text-primary-500" aria-hidden="true" />
                  Cognify-AI Workspace
                </div>
                <div className="flex gap-2">
                  <Badge variant="success" className="text-[10px]">Live</Badge>
                </div>
              </div>

              {/* Prompt row */}
              <div className="border-b border-gray-100 bg-gradient-to-r from-primary-50 to-secondary-50/50 px-5 py-4 dark:border-gray-800 dark:from-primary-950/30 dark:to-secondary-950/20">
                <div className="flex items-start gap-3">
                  <div className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-primary-600 shadow-glow-sm">
                    <Sparkles className="h-3.5 w-3.5 text-white" aria-hidden="true" />
                  </div>
                  <div className="space-y-1">
                    <div className="text-xs font-semibold text-primary-600 dark:text-primary-400">
                      Your Prompt
                    </div>
                    <p className="text-sm font-medium text-gray-800 dark:text-gray-200">
                      &ldquo;Create a modern SaaS hero with gradient headline,
                      CTA buttons, and animated background.&rdquo;
                    </p>
                  </div>
                </div>
              </div>

              {/* Code output */}
              <div className="p-5">
                <div className="mb-3 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Code2 className="h-4 w-4 text-accent-500" aria-hidden="true" />
                    <span className="text-xs font-semibold text-gray-600 dark:text-gray-300">
                      Generated Code
                    </span>
                  </div>
                  <div className="flex gap-2">
                    <Badge variant="accent" className="text-[10px]">React</Badge>
                    <Badge variant="outline" className="text-[10px]">Tailwind</Badge>
                  </div>
                </div>

                {/* Simulated code block */}
                <div className="overflow-hidden rounded-xl bg-gray-950 p-4 font-mono text-xs leading-6 dark:bg-black/60">
                  {codeLines.map((line, i) => (
                    <motion.div
                      key={i}
                      initial={{ opacity: 0, x: -8 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.6 + i * 0.06, duration: 0.3 }}
                      className={
                        line.startsWith("//")
                          ? "text-gray-500"
                          : line.includes("export") || line.includes("return")
                          ? "text-purple-400"
                          : line.includes("className")
                          ? "text-cyan-400"
                          : line.includes("<") || line.includes(">") || line.includes("/>")
                          ? "text-blue-400"
                          : line.includes('"')
                          ? "text-amber-300"
                          : "text-gray-300"
                      }
                    >
                      {line || "\u00A0"}
                    </motion.div>
                  ))}
                </div>
              </div>

              {/* Stats row */}
              <div className="grid grid-cols-3 divide-x divide-gray-100 border-t border-gray-100 dark:divide-gray-800 dark:border-gray-800">
                {[
                  { label: "Generation time", value: "1.2s", icon: Zap },
                  { label: "Lines of code", value: "48", icon: Code2 },
                  { label: "Preview ready", value: "✓", icon: PlayCircle },
                ].map(({ label, value, icon: Icon }) => (
                  <div key={label} className="flex flex-col items-center gap-0.5 py-4 px-3">
                    <Icon className="h-4 w-4 text-gray-400 dark:text-gray-500" aria-hidden="true" />
                    <div className="text-base font-bold text-gray-900 dark:text-white">{value}</div>
                    <div className="text-center text-[10px] text-gray-500 dark:text-gray-400">{label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Floating badge */}
            <motion.div
              animate={{ y: [0, -6, 0] }}
              transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
              className="absolute -right-4 -top-4 hidden rounded-2xl border border-primary-200/60 bg-white/90 px-4 py-2.5 shadow-card backdrop-blur dark:border-primary-800/40 dark:bg-gray-900/90 sm:block"
            >
              <div className="flex items-center gap-2">
                <div className="h-2 w-2 animate-pulse rounded-full bg-green-500" aria-hidden="true" />
                <span className="text-xs font-semibold text-gray-700 dark:text-gray-200">
                  AI generating…
                </span>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
